### ISSUE TITLE
Security Concern: Exposure of MongoDB Atlas Credentials in .env File

### ISSUE THREAD

**Issue by AnkitNayak-dev** [biswasprasana001/mern-chat#1]
- I've identified a security concern in this repository where MongoDB Atlas credentials, including the username and password, are exposed in the .env file. This file is publicly accessible and contains credentials that could potentially lead to unauthorized access to the MongoDB Atlas database.
- It's a best practice not to upload sensitive information, including environment variables (.env files), to a public repository on GitHub or any version control system. Instead, these files should be included in a .gitignore file to ensure they are not added to the repository.

**Comment by biswasprasana001** [comment]
I know, but as of now it's not a big deal
